#### Code to Perform the Addition of new independent feature in the Datase.csv file to get the score values of them

#### 1. Importation of the all the necessary lib. for the task to be completed and well perfromed

In [ ]:
"Library to import "
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

"Loading the numpy values"
data_values_1 = np.loadtxt('datase.csv',delimiter=',')
x = data_values_1.data
y = data_values_1

x.shape
y.shape

"Loading of new CSV file for the task "
df = pd.read_csv("datase.csv")

"""Convert to the Data Frame"""
dt=pd.DataFrame(df)
print( dt.columns)

x=dt.values

ValueError: could not convert string 'CRIM' to float64 at row 0, column 1.

In [ ]:
if 'AGE' in df.columns and 'RM' in df.columns:
    df['Age_2'] = df['AGE'] ** 2
    df['RM_2'] = df['RM'] ** 2
else:
    print("Columns 'AGE' and/or 'RM' not found in the dataset.")
  
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target,Age_2,RM_2
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806,5493.309545,39.989325
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104,3449.600164,9.079531
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000,8.410000,12.680721
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000,2027.252500,34.639111
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000,6006.290000,38.545473
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000,8850.107500,43.870759
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000,10000.000000,77.088400